/**
 * LLM service for AI-powered legal document generation.
 * Uses OpenAI-compatible API (works with OpenAI, Groq, Anthropic via proxy, etc.)
 *
 * Environment variables:
 *   OPENAI_API_KEY  — API key for the LLM provider
 *   OPENAI_BASE_URL — Base URL for the API (default: https://api.openai.com/v1)
 *   LLM_MODEL       — Model name (default: gpt-4o-mini)
 */

const DEFAULT_BASE_URL = "https://api.openai.com/v1";
const DEFAULT_MODEL = "gpt-4o-mini";
const DEFAULT_MAX_TOKENS = 4096;
const DEFAULT_TEMPERATURE = 0.3;

export interface GenerateDocumentParams {
  documentType: string;
  formData: Record<string, string>;
  language: "en" | "hi";
}

export interface GenerateDocumentResult {
  content: string;
  tokens: number;
}

function isConfigured(): boolean {
  return Boolean(
    process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY.trim().length > 0
  );
}

function getBaseUrl(): string {
  return (process.env.OPENAI_BASE_URL || DEFAULT_BASE_URL).replace(/\/$/, "");
}

function getModel(): string {
  return process.env.LLM_MODEL || DEFAULT_MODEL;
}

/**
 * Build the system prompt for legal document drafting.
 * Each document type has specific instructions.
 */
function buildSystemPrompt(
  documentType: string,
  language: "en" | "hi"
): string {
  const langInstruction =
    language === "hi"
      ? "You MUST write the entire document in Hindi (हिन्दी) using the Devanagari script. Use formal, legal Hindi."
      : "You MUST write the entire document in English. Use formal, professional legal English as used in Indian courts and contracts.";

  const typeInstructions = getTypeInstructions(documentType);

  return `You are an Indian legal document drafting assistant. You are an expert in Indian law, including but not limited to the Indian Contract Act, 1872, the Indian Partnership Act, 1932, the Indian Stamp Act, 1899, the Information Technology Act, 2000, the Code of Civil Procedure, 1908, the Indian Penal Code, 1860, the Indian Oaths Act, 1969, the Negotiable Instruments Act, 1881, and all relevant state-specific legislation such as Rent Control Acts and Shops & Establishments Acts.

Your task is to draft a complete, professional legal document based on the user's inputs. The document must:
1. Have proper legal formatting with clear party names, recitals (WHEREAS clauses), operative sections (NOW THEREFORE), numbered clauses, schedules (if applicable), signature blocks, and witness sections.
2. Reference relevant Indian statutes and legal principles where appropriate within the body.
3. Use the specific user-provided details (names, addresses, dates, amounts, terms) exactly as given — do not invent or modify them.
4. Maintain a professional, formal legal tone appropriate for Indian legal practice.
5. Include a mandatory AI disclaimer at the very bottom of the document, separated by a horizontal line.

${langInstruction}

${typeInstructions}

CRITICAL FORMATTING RULES:
- Output ONLY the plain text of the legal document — no markdown, no HTML, no code fences.
- Use ALL CAPS for document titles and section headings.
- Use blank lines to separate sections.
- Number clauses using standard legal numbering: 1., 1.1, (a), (i), etc.
- For party references, use the actual names provided by the user, not placeholders.
- Always include complete signature blocks with lines for signatures, names, dates, and places.
- Add witness signature blocks where appropriate (e.g., for Partnership Deeds and Affidavits).
- Use "_______________" for blank signature/date lines that the user must fill.

MANDATORY DISCLAIMER (include EXACTLY as the final section, after a line of "========================" or similar separator):

DISCLAIMER: This document was generated by Munsif AI, an artificial intelligence tool, and is provided as a draft template only. It is NOT a substitute for professional legal advice from a licensed advocate. You should have this document reviewed by a qualified legal professional before use. Munsif AI is a technology platform, not a law firm. Use of this document does not create an attorney-client relationship. Munsif AI makes no representations or warranties regarding the legal sufficiency, accuracy, or completeness of this document for your specific circumstances.`;
}

function getTypeInstructions(documentType: string): string {
  const normalized = documentType.toLowerCase().replace(/\s+/g, "-");

  switch (normalized) {
    case "rental-agreement":
    case "rental agreement":
      return `DOCUMENT TYPE: RENTAL AGREEMENT

This is a rental/lease agreement under Indian law. Include these specific elements:
- Clear identification of LESSOR (Landlord) and LESSEE (Tenant) with full addresses.
- Detailed property description including type (residential/commercial), furnishing status, and complete address.
- Rent terms: monthly rent amount, security deposit amount (typically 2-3 months' rent), lease start date, lease duration, and notice period.
- Reference to applicable state Rent Control Act based on the property location.
- Maintenance responsibilities allocation between landlord and tenant.
- Restrictions on subletting, pet policy, and any special conditions.
- Clause about stamp duty and registration: reference the Indian Stamp Act, 1899 and applicable state stamp acts. Note that leases over 11 months typically require registration under the Registration Act, 1908.
- Utility payment responsibilities.
- Eviction grounds referencing applicable rent control legislation.
- Standard clauses: quiet enjoyment, landlord's right of inspection, alterations, indemnity.
- The governing law section should reference the Indian Contract Act, 1872.`;

    case "nda":
    case "non-disclosure agreement":
      return `DOCUMENT TYPE: NON-DISCLOSURE AGREEMENT (NDA)

This is a confidentiality/non-disclosure agreement under Indian law. Include:
- Clear identification of DISCLOSING PARTY and RECEIVING PARTY with full addresses.
- Detailed definition of "Confidential Information" — broad enough to cover all disclosures but with standard exclusions (public domain, prior knowledge, independent development, legal compulsion).
- Purpose of disclosure clause — clearly state the limited purpose for which information is shared.
- Obligations of the Receiving Party: confidentiality, non-use, limited access, non-disclosure to third parties.
- Duration of confidentiality obligations (typically 2-5 years or perpetual for trade secrets).
- Non-solicitation clause (if applicable): restriction on poaching employees/clients.
- Non-compete clause (if applicable): note that under Section 27 of the Indian Contract Act, 1872, agreements in restraint of trade are void unless reasonable. For NDAs, limited non-compete during the engagement period is generally enforceable.
- Remedies for breach: injunctive relief, specific performance, damages. Reference Sections 38 and 39 of the Specific Relief Act, 1963 for injunctive relief.
- Governing law and jurisdiction clause specifying the chosen Indian state.
- Dispute resolution: arbitration clause under the Arbitration and Conciliation Act, 1996 if selected, or court jurisdiction.
- Return/destruction of confidential information upon termination.`;

    case "employment-contract":
    case "employment contract":
      return `DOCUMENT TYPE: EMPLOYMENT CONTRACT

This is an employment agreement governed by Indian labour laws. Include:
- Identification of EMPLOYER (Company) and EMPLOYEE with full details.
- Job title, department, reporting structure, and employment type (full-time/part-time/contract).
- Date of commencement and probation period (typically 3-6 months).
- Compensation: CTC breakdown including basic salary, HRA, conveyance, medical allowance, PF contribution, gratuity eligibility, bonus.
- Reference to: Employees' Provident Funds and Miscellaneous Provisions Act, 1952; Payment of Gratuity Act, 1972; Payment of Bonus Act, 1965; Employees' State Insurance Act, 1948 (where applicable).
- Working hours, weekly off, leave entitlement (earned leave, sick leave, casual leave) compliant with the applicable state Shops & Establishments Act and the Factories Act, 1948 (if applicable).
- Notice period for termination/resignation (typically 30-90 days).
- Confidentiality obligations during and after employment.
- Non-compete clause (note: under Section 27 of the Indian Contract Act, 1872, post-employment non-competes are generally unenforceable except when protecting trade secrets/business goodwill, but reasonable restrictions during employment are valid).
- IP assignment clause: all work product created during employment belongs to the employer.
- Code of conduct, disciplinary procedure, and grounds for termination.
- Statutory compliance acknowledgment.
- Governing law and jurisdiction.`;

    case "freelance-agreement":
    case "freelance agreement":
    case "freelance / service agreement":
    case "service agreement":
      return `DOCUMENT TYPE: FREELANCE / INDEPENDENT CONTRACTOR / SERVICE AGREEMENT

This is a contract for services (not employment) governed by the Indian Contract Act, 1872. Include:
- Identification of CLIENT and FREELANCER/SERVICE PROVIDER with full details.
- Clear and detailed scope of work/project description with specific deliverables and acceptance criteria.
- Timeline/deadline and milestones for delivery.
- Payment terms: total project fee, payment schedule (upfront/milestone/completion), invoicing procedure.
- Late payment penalty/interest clause referencing the Interest on Delayed Payments to Small Scale and Ancillary Industrial Undertakings Act or contractual interest rate.
- TDS provisions: reference Section 194J of the Income Tax Act, 1961 (fees for professional/technical services — 10% TDS if applicable) or Section 194C (contract payments — 1-2% TDS).
- GST clause: note GST applicability if freelancer turnover exceeds threshold under CGST Act, 2017.
- Independent contractor relationship disclaimer — explicitly state that no employer-employee relationship is created.
- Intellectual property ownership: who owns the deliverables (work-for-hire or assignment clause).
- Revision rounds and scope change procedure.
- Termination clause with notice period for both parties.
- Confidentiality obligations.
- Indemnification and limitation of liability.
- Governing law and jurisdiction.`;

    case "partnership-deed":
    case "partnership deed":
      return `DOCUMENT TYPE: PARTNERSHIP DEED

This is a partnership deed under the Indian Partnership Act, 1932. Include:
- Name of the partnership firm.
- Principal place of business with complete address.
- Nature of business — detailed description of the business activities.
- Full details of all partners (at least 2) with names and addresses.
- Date of commencement of partnership.
- Duration of partnership: "at will" or for a fixed period.
- Capital contribution of each partner in INR.
- Profit and loss sharing ratio among partners.
- Interest on capital and drawings (if any).
- Remuneration/salary to working partners (reference Section 40(b) of Income Tax Act, 1961 for tax deductibility limits).
- Banking arrangements: authorized signatories for firm's bank account (jointly or severally).
- Books of accounts, audit requirements, and financial year.
- Rights and duties of partners as per Sections 12-17 of the Indian Partnership Act, 1932.
- Retirement, expulsion, and admission of new partners procedure.
- Dissolution provisions referencing Sections 39-55 of the Indian Partnership Act, 1932.
- Dispute resolution: arbitration under the Arbitration and Conciliation Act, 1996 if selected.
- Note about partnership registration under Section 58 of the Indian Partnership Act, 1932 with the Registrar of Firms.
- Witness signature blocks.`;

    case "legal-notice":
    case "legal notice":
      return `DOCUMENT TYPE: FORMAL LEGAL NOTICE

This is a formal legal notice sent by one party to another through an advocate or directly. Include:
- Sender's full details (name and address) positioned at top.
- Recipient's full details (name and address).
- Date of notice.
- Reference/subject line in caps: "LEGAL NOTICE UNDER [relevant section/provision]".
- Opening: "Under instructions from and on behalf of my client, [Name], I hereby serve upon you the following legal notice:"
- Detailed statement of facts giving rise to the grievance, in chronological order.
- Legal basis: specific reference to applicable statutory provisions (e.g., Section 138 of the Negotiable Instruments Act, 1881 for cheque bounce; Section 73 of the Indian Contract Act, 1872 for breach of contract).
- Specific relief/demand: exact amount claimed, actions required, or performance demanded.
- Deadline for compliance (typically 15-30 days).
- Consequences of non-compliance: warning that legal proceedings (civil/criminal) will be initiated without further notice.
- "Without prejudice" clause.
- Signature block: "Yours faithfully," followed by advocate details (if applicable) and sender's name.
- CC notation if copies sent to others.
- Note about mode of service: Registered Post AD, Email, or both.
- The tone must be formal, firm, and legally precise — this is often a prerequisite to filing a suit.`;

    case "affidavit":
      return `DOCUMENT TYPE: AFFIDAVIT (SWORN STATEMENT)

This is a sworn affidavit under the Indian Oaths Act, 1969 and Order XIX of the Code of Civil Procedure, 1908. Include:
- Heading: "AFFIDAVIT" centered at top.
- Reference: "IN THE MATTER OF: [subject]" and "AFFIDAVIT OF: [Deponent's full name]".
- Deponent's full particulars: name, age (as on date), parentage (S/o or D/o or W/o), and complete residential address.
- The deponent's declaration: "I, [Name], the above-named Deponent, do hereby solemnly affirm and state on oath as follows:"
- Numbered paragraphs of facts stated in first person, each paragraph dealing with one fact.
- Each paragraph to be a clear, factual statement — no arguments or legal submissions.
- Final paragraph: "I say that the contents of this affidavit are true and correct to the best of my knowledge and belief. Nothing material has been concealed therefrom. No part of it is false."
- Verification section with date and place.
- Notary attestation block (if notary details provided): notary name, registration number, seal and signature.
- Reference to penalties for false statements under Sections 193, 199, and 200 of the Indian Penal Code, 1860.
- Signature lines for deponent and notary.`;

    case "terms-of-service":
    case "terms of service":
      return `DOCUMENT TYPE: TERMS OF SERVICE / TERMS & CONDITIONS

This is a Terms of Service agreement for a website, app, or SaaS product governed by Indian law. Include:
- Company identification: legal name, registered address, contact email.
- Effective date and last updated date.
- Definitions section for key terms.
- Description of services offered.
- Eligibility criteria (e.g., 18+ years, capable of contracting under Indian Contract Act, 1872).
- Account registration, user obligations, and responsibilities.
- Acceptable use policy with prohibited activities (reference IT Act, 2000 — Section 43 and 66 for unauthorized access, Section 67 for prohibited content).
- Intellectual property rights: company's ownership of platform, user's ownership of their content, license grant.
- Payment terms (if applicable): pricing, billing, refunds, GST.
- Privacy and data collection: reference to separate Privacy Policy, compliance with Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and the Digital Personal Data Protection Act, 2023.
- Third-party services and links disclaimer.
- Limitation of liability and disclaimer of warranties.
- Indemnification by user.
- Termination and suspension of accounts.
- Governing law and jurisdiction (specific Indian state).
- Dispute resolution mechanism.
- Modification of terms with notice provision.
- Grievance officer details as required under IT Rules, 2021 — name, designation, email, and address of the Grievance Officer.
- Contact information.
- The document should be structured as a click-wrap or browse-wrap agreement suitable for digital acceptance.`;

    default:
      return `DOCUMENT TYPE: ${documentType}

Draft a formal Indian legal document of this type. Follow standard Indian legal formatting conventions. Reference applicable Indian statutes where relevant. Include proper party identification, recitals, operative clauses, signature blocks, and the mandatory AI disclaimer.`;
  }
}

/**
 * Build the user prompt with the form data.
 */
function buildUserPrompt(
  documentType: string,
  formData: Record<string, string>,
  language: "en" | "hi"
): string {
  const langLabel = language === "hi" ? "Hindi (हिन्दी)" : "English";
  const today = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let prompt = `Please draft a complete ${documentType} in ${langLabel} based on the following information provided by the user. Today's date for reference is ${today}.

USER-PROVIDED INFORMATION:
${JSON.stringify(formData, null, 2)}

INSTRUCTIONS:
1. Draft the FULL, complete document — do not leave any sections as placeholders or "to be filled later" except for signature lines.
2. Use the exact values provided above — names, addresses, dates, amounts, and other details must match precisely.
3. If any critical information is missing, use reasonable standard language but flag it with [TO BE INSERTED: description] in the text.
4. The document must be ready for review with all clauses written out in full. Do not use abbreviations like "etc." or "as above" to skip content — write each clause completely.
5. Include the mandatory AI disclaimer at the end.`;

  return prompt;
}

/**
 * Generate a legal document using the LLM.
 * Returns the generated text and token count.
 */
export async function generateLegalDocument(
  params: GenerateDocumentParams
): Promise<GenerateDocumentResult> {
  if (!isConfigured()) {
    throw new Error(
      "LLM API key not configured. Set OPENAI_API_KEY environment variable."
    );
  }

  const baseUrl = getBaseUrl();
  const model = getModel();
  const apiKey = process.env.OPENAI_API_KEY!;

  const systemPrompt = buildSystemPrompt(params.documentType, params.language);
  const userPrompt = buildUserPrompt(
    params.documentType,
    params.formData,
    params.language
  );

  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: DEFAULT_TEMPERATURE,
      max_tokens: DEFAULT_MAX_TOKENS,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text().catch(() => "Unknown error");
    throw new Error(
      `LLM API error (${response.status}): ${errorBody.slice(0, 300)}`
    );
  }

  const data = await response.json();

  const content: string =
    data.choices?.[0]?.message?.content || "";
  const tokens: number =
    data.usage?.total_tokens ??
    data.usage?.completion_tokens ??
    0;

  if (!content.trim()) {
    throw new Error("LLM returned empty response.");
  }

  return { content: content.trim(), tokens };
}

export { isConfigured };
