/**
 * PDF generation utilities.
 * 
 * In production, this will use a serverless PDF generation service
 * (or Puppeteer/Playwright running in a worker). For now, it provides
 * the interface and placeholder logic.
 */

export interface PDFGenerationOptions {
  html: string;
  fileName: string;
  landscape?: boolean;
  margin?: { top: string; right: string; bottom: string; left: string };
}

export interface PDFResult {
  url: string;
  fileName: string;
  sizeBytes: number;
}

/**
 * Generate a PDF from HTML content.
 * 
 * TODO: In production, use:
 * - Puppeteer/Playwright on server-side for HTML-to-PDF
 * - Or a cloud PDF service (e.g., DocRaptor, Prince XML)
 * - Store the resulting PDF in cloud storage (S3, R2, etc.)
 */
export async function generatePDF(
  options: PDFGenerationOptions
): Promise<PDFResult> {
  // Placeholder: In production, this would:
  // 1. Launch a headless browser
  // 2. Render the HTML with proper print styles
  // 3. Generate the PDF
  // 4. Upload to storage and return the URL
  
  throw new Error(
    "PDF generation not yet implemented. Connect a PDF service in production."
  );
}

/**
 * Build the full HTML document for PDF rendering.
 * Includes the AI disclaimer and proper print styles.
 */
export function buildDocumentHTML(
  title: string,
  bodyContent: string,
  disclaimer: string,
  language: "en" | "hi" = "en"
): string {
  const lang = language === "hi" ? "hi" : "en";
  const direction = language === "hi" ? "rtl" : "ltr";
  
  return `<!DOCTYPE html>
<html lang="${lang}" dir="${direction}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — Munsif AI</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'Inter', 'Noto Sans Devanagari', sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1c1917;
      padding: 2cm;
      max-width: 210mm;
      margin: 0 auto;
    }
    
    h1 {
      font-size: 18pt;
      font-weight: 700;
      margin-bottom: 24px;
      color: #1c544d;
      border-bottom: 2px solid #1c544d;
      padding-bottom: 8px;
    }
    
    h2 {
      font-size: 14pt;
      font-weight: 600;
      margin-top: 20px;
      margin-bottom: 8px;
      color: #292524;
    }
    
    p {
      margin-bottom: 8px;
    }
    
    .disclaimer-box {
      margin-top: 40px;
      padding: 12px 16px;
      border: 1px solid #f06404;
      border-left: 4px solid #f06404;
      background: #fff8ed;
      font-size: 9pt;
      color: #9e3d0d;
      border-radius: 4px;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #e7e5e4;
      font-size: 8pt;
      color: #78716c;
      text-align: center;
    }
    
    @media print {
      body { padding: 0; }
      .disclaimer-box { break-inside: avoid; }
    }
  </style>
</head>
<body>
  ${bodyContent}
  
  <div class="disclaimer-box">
    <strong>⚠️ ${disclaimer}</strong>
  </div>
  
  <div class="footer">
    Generated by Munsif AI • munsif.ai • This is an AI-generated document
  </div>
</body>
</html>`;
}
