/**
 * PDF generation service using Playwright (Chromium).
 *
 * Renders HTML to A4 PDF with legal-document quality:
 * - Serif typography
 * - Proper margins for binding
 * - Print backgrounds
 * - Page numbers
 *
 * Architecture note: Playwright runs headless Chromium server-side.
 * In production, consider offloading to a dedicated worker/sandbox for scale.
 */

import { chromium, type Browser } from "playwright";
import { buildPdfHtml, type PdfTemplateOptions } from "./pdf-template";

export interface GeneratePdfOptions {
  /** The document body content (plain text or basic HTML) */
  bodyContent: string;
  /** Document title (e.g., "Rental Agreement") */
  title: string;
  /** Document type label (e.g., "Rental Agreement") */
  documentType: string;
  /** Language for i18n */
  language?: "en" | "hi";
}

export interface GeneratePdfResult {
  /** The PDF data as a Buffer */
  buffer: Buffer;
  /** Suggested filename */
  fileName: string;
  /** Size in bytes */
  sizeBytes: number;
}

// Singleton browser instance for reuse across requests.
// Playwright recommends a single browser instance per process.
let browserPromise: Promise<Browser> | null = null;

async function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    browserPromise = chromium.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
      ],
    });
  }
  return browserPromise;
}

/**
 * Cleanup browser instance. Call on server shutdown.
 */
export async function closeBrowser(): Promise<void> {
  if (browserPromise) {
    const browser = await browserPromise;
    await browser.close();
    browserPromise = null;
  }
}

/**
 * Generate a professional PDF from document content.
 *
 * @param options - Document content and metadata
 * @returns PDF buffer and metadata
 */
export async function generatePdf(
  options: GeneratePdfOptions
): Promise<GeneratePdfResult> {
  const {
    bodyContent,
    title,
    documentType,
    language = "en",
  } = options;

  // Format generation timestamp in Indian locale
  const now = new Date();
  const generationTimestamp = now.toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

  // Build the full HTML document
  const html = buildPdfHtml({
    title,
    documentType,
    bodyContent,
    generationTimestamp,
    language,
  });

  const browser = await getBrowser();
  const context = await browser.newContext({
    // Ensure consistent rendering regardless of system locale
    locale: language === "hi" ? "hi-IN" : "en-IN",
  });

  const page = await context.newPage();

  try {
    // Set the HTML content
    await page.setContent(html, {
      waitUntil: "networkidle",
      timeout: 15000,
    });

    // Generate PDF with legal-document settings
    const pdfBuffer = await page.pdf({
      format: "A4",
      margin: {
        top: "25mm",
        bottom: "25mm",
        left: "20mm",
        right: "20mm",
      },
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: "<span></span>", // Minimal header — info is in the document
      footerTemplate: `
        <div style="width: 100%; font-family: Georgia, serif; font-size: 8pt; color: #78716c; text-align: center; padding: 0 20mm;">
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          <span style="margin-left: 24px;">Generated by Munsif AI &bull; AI-Generated Document Draft</span>
        </div>
      `,
      preferCSSPageSize: true,
    });

    // Generate filename
    const safeName = title
      .replace(/[^a-zA-Z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .toLowerCase();
    const fileName = `${safeName}-Munsif-AI.pdf`;

    return {
      buffer: Buffer.from(pdfBuffer),
      fileName,
      sizeBytes: pdfBuffer.length,
    };
  } finally {
    // Always close the page and context to prevent memory leaks
    await page.close();
    await context.close();
    // Note: Keep the browser alive for reuse across requests
  }
}

/**
 * Generate a PDF directly from a full HTML string.
 * Use this when you already have a complete HTML document
 * (e.g., for testing or custom templates).
 */
export async function generatePdfFromHtml(
  html: string,
  options: {
    title: string;
    documentType: string;
  }
): Promise<Buffer> {
  const browser = await getBrowser();
  const context = await browser.newContext({ locale: "en-IN" });
  const page = await context.newPage();

  try {
    await page.setContent(html, {
      waitUntil: "networkidle",
      timeout: 15000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      margin: {
        top: "25mm",
        bottom: "25mm",
        left: "20mm",
        right: "20mm",
      },
      printBackground: true,
      displayHeaderFooter: true,
      footerTemplate: `
        <div style="width: 100%; font-family: Georgia, serif; font-size: 8pt; color: #78716c; text-align: center; padding: 0 20mm;">
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          <span style="margin-left: 24px;">Generated by Munsif AI &bull; AI-Generated Document Draft</span>
        </div>
      `,
      preferCSSPageSize: true,
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await page.close();
    await context.close();
  }
}
